import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#d3e4fe",
        "primary": "#091426",
        "primary-container": "#1e293b",
        "surface-container-high": "#dce9ff",
        "primary-fixed": "#d8e3fb",
        "on-primary": "#ffffff",
        "outline": "#75777d",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "inverse-primary": "#bcc7de",
        "on-primary-fixed-variant": "#3c475a",
        "inverse-surface": "#213145",
        "surface-variant": "#d3e4fe",
        "tertiary-fixed": "#fadfb8",
        "tertiary-container": "#35260c",
        "on-primary-container": "#8590a6",
        "outline-variant": "#c5c6cd",
        "on-surface-variant": "#45474c",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#b4c5ff",
        "surface-bright": "#f8f9ff",
        "secondary": "#0051d5",
        "on-secondary-fixed-variant": "#003ea8",
        "inverse-on-surface": "#eaf1ff",
        "secondary-container": "#316bf3",
        "on-tertiary-fixed-variant": "#564427",
        "surface": "#f8f9ff",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#0b1c30",
        "on-background": "#0b1c30",
        "background": "#f8f9ff",
        "surface-dim": "#cbdbf5",
        "on-primary-fixed": "#111c2d",
        "surface-container": "#e5eeff",
        "tertiary-fixed-dim": "#ddc39d",
        "on-tertiary-fixed": "#271902",
        "surface-tint": "#545f73",
        "on-tertiary": "#ffffff",
        "error": "#ba1a1a",
        "surface-container-low": "#eff4ff",
        "primary-fixed-dim": "#bcc7de",
        "on-tertiary-container": "#a38c6a",
        "secondary-fixed": "#dbe1ff",
        "on-secondary-container": "#fefcff",
        "tertiary": "#1e1200",
        "on-secondary-fixed": "#00174b",
        "success": "#10b981", 
        "success-dim": "rgba(16, 185, 129, 0.05)",
        "secondary-trust": "#2563eb", 
        "secondary-trust-dim": "rgba(37, 99, 235, 0.05)",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "24px",
        "container-max-width": "1280px",
        "base": "8px",
        "margin-mobile": "16px",
        "margin-desktop": "40px"
      },
      fontFamily: {
        "headline-lg": ["var(--font-inter)"],
        "data-mono": ["var(--font-jetbrains)"],
        "body-md": ["var(--font-inter)"],
        "label-caps": ["var(--font-jetbrains)"],
        "body-sm": ["var(--font-inter)"],
        "headline-lg-mobile": ["var(--font-inter)"],
        "display-lg": ["var(--font-inter)"],
        "title-md": ["var(--font-inter)"]
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "data-mono": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "title-md": ["20px", { lineHeight: "28px", fontWeight: "600" }]
      }
    }
  },
  plugins: [],
}
export default config
